server:
  port: 5000
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day_scheduler?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC
    password: mysql
    username: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
